# Static web site compiler
FROM node:12

ARG ETH_NETWORK_ID=goerli
ENV ETH_NETWORK_ID=${ETH_NETWORK_ID}
ARG BOOTNODES_URL_READ_ONLY
ENV BOOTNODES_URL_READ_ONLY=${BOOTNODES_URL_READ_ONLY}
ARG BOOTNODES_URL_RW
ENV BOOTNODES_URL_RW=${BOOTNODES_URL_RW}
ARG APP_LINKING_DOMAIN
ENV APP_LINKING_DOMAIN=${APP_LINKING_DOMAIN}
ARG REGISTER_URL
ENV REGISTER_URL=${REGISTER_URL}
ARG ACTION_VISIBILITY_URL
ENV ACTION_VISIBILITY_URL=${ACTION_VISIBILITY_URL}
ARG REGISTRY_GATEWAY_URL
ENV REGISTRY_GATEWAY_URL=${REGISTRY_GATEWAY_URL}
ARG REGISTRY_GATEWAY_PUB_KEY
ENV REGISTRY_GATEWAY_PUB_KEY=${REGISTRY_GATEWAY_PUB_KEY}

ADD . /app
WORKDIR /app
RUN npm install && npm run build

# Static web site is available on /app/build
CMD npm run export
